### ISSUE TITLE
Neodash multiselect parameter issue

### ISSUE THREAD

**Issue by Deepaksarda** [neo4j-labs/neodash#883]
Version: v2.4.6
Hi Team,

We had created dashboard in neodash with multiselect filter, which was working fine till last week and suddenly getting below error:
An unexpected error occurred. Try refreshing the component.

TypeError: Be.map is not a function
at https://neodash.graphapp.io/bundle.js:2:8628548
at ti (https://neodash.graphapp.io/bundle.js:152:1747545)
at Ii (https://neodash.graphapp.io/bundle.js:152:1755689)
at Hl (https://neodash.graphapp.io/bundle.js:152:1801680)
at Ec (https://neodash.graphapp.io/bundle.js:152:1786917)
at _c (https://neodash.graphapp.io/bundle.js:152:1786845)
at wc (https://neodash.graphapp.io/bundle.js:152:1786708)
at hc (https://neodash.graphapp.io/bundle.js:152:1783695)
at https://neodash.graphapp.io/bundle.js:152:1733467
at n.unstable_runWithPriority (https://neodash.graphapp.io/bundle.js:152:1904603)
at Ho (https://neodash.graphapp.io/bundle.js:152:1733244)
at Wo (https://neodash.graphapp.io/bundle.js:152:1733412)
at $o (https://neodash.graphapp.io/bundle.js:152:1733347)
at Le (https://neodash.graphapp.io/bundle.js:152:1804157)
at Yn (https://neodash.graphapp.io/bundle.js:152:1712063)
at HTMLBodyElement.t (https://neodash.graphapp.io/bundle.js:152:533756)

**Comment by alfredorubin96** [comment]
Hi @Deepaksarda, thank you for the creating this issue. This has already been fixed in the PR #881 made by @mariusconjeaud

**Comment by Deepaksarda** [comment]
Hi Alfredo,

Seems we are getting new error in V2.4.7 'Invalid input for function
'size()': Expected a String or List, got: Double(NaN)' whereas same
dashboard is working fine on V2.4.6
I was just checking size(parameter)
Regards
Deepak

**Comment by Deepaksarda** [comment]
Hi Team,

I had check that and multiselect error is fixed now but it has generated another bug.
I had created 5 different filters (below logic) and once dashboard is load if I just select only one filter it shows me no data retrieve. I need to select all filters first and deselect last 4 than report shows data to me.
Below is Cypher query:
with 
'Supplier' as Supplier_Type,
              'END_MODEL_PLANT' as End_Model_PLANT,
              'Customer' as Customer_Value,
              ($neodash_customer_nodes_customer_group_name) as Customer,
              ($neodash_prog_master_family_prog_master_name) as program,
              ($neodash_end_model_plant_node_material_id) As End_Model,
              ($neodash_component_plant_node_material_id) as Component,
              ($neodash_supplier_node_location_desc) as Supplier
WITH
End_Model_PLANT, Customer_Value, Customer, program, End_Model, Component, Supplier,
CASE WHEN (Customer)<>[] THEN ['c.Customer_Group_Name in $Customer'] ELSE [] END
+ CASE WHEN (program)<>[]  THEN ['p.Prog_Master_Name in $program'] ELSE [] END
+ CASE WHEN (End_Model)<>[] THEN ['np.Node_Material_Id in $End_Model'] ELSE [] END
+ CASE WHEN (Component)<>[]  THEN ['n1.Node_Material_Id in $Component'] ELSE [] END
+ CASE WHEN (Supplier)<>[]  THEN ['n1.Node_Location_Desc in $Supplier'] ELSE [] END 
as arrayOfFilters
WITH
'Match path=
    (n1:Nodes)-[:GO_TO*1..6]->
              (np:END_MODEL_PLANT)-[:GO_TO] ->
              (n2:Customer)-[:PART_OF]->
              (c:Customer_Nodes), (n2)-[:SUB_SET_OF]->(p:Prog_Master_Family)
' + CASE WHEN SIZE(arrayOfFilters)>0 THEN ' WHERE ' + apoc.text.join(arrayOfFilters,' 
AND ') ELSE '' END + '
Return 
path limit 1000
' as query,
{
Customer:Customer, program:program, End_Model:End_Model, Component:Component, Supplier:Supplier
} as params
CALL apoc.cypher.run(query, params) 
YIELD value
WITH value.path as path
Return path

**Comment by mariusconjeaud** [comment]
This is fixed now in 2.4.7
